export const LISTINGS = [
  {
    id: 'l_001',
    title: 'Covered Apt Slot — Indiranagar',
    location: '12th Main, Indiranagar',
    area: 'Indiranagar',
    type: 'apartment',
    nearMetro: true,
    metroStation: 'Indiranagar Metro',
    metroDistance: '180m',
    nearMall: false,
    vehicleTypes: ['4-wheeler'],
    features: ['Covered', 'CCTV', 'Gated', '24x7'],
    pricing: { hourly: 40, daily: 200, weekly: 1100, monthly: 3500, yearly: 36000 },
    rating: 4.8,
    reviews: 34,
    kycVerified: true,
    hostName: 'Ravi K.',
    hostAvatar: 'RK',
    available: true,
    lat: 12.9784,
    lng: 77.6408,
    images: ['apt'],
  },
  {
    id: 'l_002',
    title: 'Open Plot Near Whitefield Metro',
    location: 'ITPL Road, Whitefield',
    area: 'Whitefield',
    type: 'openPlot',
    nearMetro: true,
    metroStation: 'Whitefield Metro',
    metroDistance: '200m',
    nearMall: false,
    vehicleTypes: ['2-wheeler', '4-wheeler', 'suv'],
    features: ['Open', 'CCTV', '24x7'],
    pricing: { hourly: 25, daily: 120, weekly: 700, monthly: 1800, yearly: 18000 },
    rating: 4.6,
    reviews: 21,
    kycVerified: true,
    hostName: 'Suresh M.',
    hostAvatar: 'SM',
    available: true,
    lat: 12.9698,
    lng: 77.7499,
    images: ['plot'],
  },
  {
    id: 'l_003',
    title: 'Private Spot Near Phoenix Mall',
    location: 'Whitefield, 300m from mall',
    area: 'Whitefield',
    type: 'commercial',
    nearMetro: false,
    nearMall: true,
    mallName: 'Phoenix Marketcity',
    mallDistance: '300m',
    vehicleTypes: ['4-wheeler', 'suv'],
    features: ['Covered', 'CCTV', 'Security Guard'],
    pricing: { hourly: 30, daily: 180, weekly: 900, monthly: 2800, yearly: 28000 },
    rating: 4.9,
    reviews: 56,
    kycVerified: true,
    hostName: 'Anita R.',
    hostAvatar: 'AR',
    available: true,
    lat: 12.9968,
    lng: 77.6962,
    images: ['commercial'],
  },
  {
    id: 'l_004',
    title: 'Bike Parking — HSR Layout',
    location: 'Sector 2, HSR Layout',
    area: 'HSR Layout',
    type: 'apartment',
    nearMetro: false,
    nearMall: false,
    vehicleTypes: ['2-wheeler'],
    features: ['Covered', 'Gated'],
    pricing: { hourly: 15, daily: 60, weekly: 350, monthly: 800, yearly: 8000 },
    rating: 4.7,
    reviews: 18,
    kycVerified: true,
    hostName: 'Priya N.',
    hostAvatar: 'PN',
    available: true,
    lat: 12.9121,
    lng: 77.6446,
    images: ['bike'],
  },
  {
    id: 'l_005',
    title: 'Commercial Basement — Koramangala',
    location: '5th Block, Koramangala',
    area: 'Koramangala',
    type: 'commercial',
    nearMetro: false,
    nearMall: true,
    mallName: 'Forum Mall',
    mallDistance: '150m',
    vehicleTypes: ['4-wheeler', 'suv'],
    features: ['Covered', 'CCTV', '24x7', 'Security Guard'],
    pricing: { hourly: 35, daily: 200, weekly: 1000, monthly: 4000, yearly: 42000 },
    rating: 4.5,
    reviews: 42,
    kycVerified: true,
    hostName: 'Deepak J.',
    hostAvatar: 'DJ',
    available: true,
    lat: 12.9352,
    lng: 77.6245,
    images: ['commercial'],
  },
  {
    id: 'l_006',
    title: 'Vacant Land Near MG Road Metro',
    location: 'Near MG Road Metro Gate 3',
    area: 'MG Road',
    type: 'openPlot',
    nearMetro: true,
    metroStation: 'MG Road Metro',
    metroDistance: '120m',
    nearMall: false,
    vehicleTypes: ['2-wheeler', '4-wheeler'],
    features: ['Open', '24x7'],
    pricing: { hourly: 30, daily: 150, weekly: 800, monthly: 2500, yearly: 25000 },
    rating: 4.3,
    reviews: 9,
    kycVerified: false,
    hostName: 'Venkat S.',
    hostAvatar: 'VS',
    available: true,
    lat: 12.9753,
    lng: 77.6069,
    images: ['plot'],
  },
];

export const METRO_STATIONS = [
  'Indiranagar', 'Whitefield', 'MG Road', 'Marathahalli',
  'Koramangala', 'Jayanagar', 'Hebbal', 'Banashankari',
  'Baiyappanahalli', 'Majestic', 'Yeshwanthpur',
];

export const AREAS = [
  'Indiranagar', 'Whitefield', 'Koramangala', 'HSR Layout',
  'MG Road', 'Jayanagar', 'Hebbal', 'Electronic City',
  'Marathahalli', 'Bannerghatta Road',
];
